# Generated by Django 5.0.7 on 2024-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
