# Generated by Django 5.0.7 on 2024-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0003_book_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='emprestado',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
