# Generated by Django 5.0.7 on 2024-08-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='emprestado',
        ),
        migrations.AddField(
            model_name='book',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
