# Generated by Django 5.0.7 on 2024-08-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0006_remove_book_user_remove_emprestimo_emprestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
